import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '../lib/utils';
import dynamic from 'next/dynamic';

const SideNavbar = dynamic(() => import('@/components/SideNavbar'), {
  ssr: false,
  suspense: true,
  loading: () => <div>loading...</div>,
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Shadcn Dashboard',
  description: 'Generated by create next app',
  icons: {
    icon: './icons8-dashboard-50.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen w-full bg-white text-black flex ',
          inter.className
        )}
      >
        {/* sidebar */}
        <SideNavbar />
        {/* main page */}

        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
